version: "3.8"
services:
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: always
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    env_file:
      - .env
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.max_content_length=500mb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - my_network
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_URL=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - SERVER_MAXPAYLOADBYTES=524288000
    depends_on:
      - elasticsearch
    networks:
      - my_network


networks:
  my_network:
      driver: bridge
      
volumes:
  esdata: