server:
  port: 8011


spring:
  application:
    name: elastic-search-service
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200





#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      healthcheck:
#        enabled: true
#  instance:
#    prefer-ip-address: true